### ISSUE TITLE
Request for pretrained weights 

### ISSUE THREAD

**Issue by yiyeChen** [antoalli/L2G#3]
Thanks for the great work!

Wondering whether you can release the pre-trained weights? Thanks!

**Comment by Andyyoung0507** [comment]
Hi, I am interested in this excellent work. 
Could you please release the pre-trained weights? @antoalli @mrudorfer Thanks!
Did you get the pre-trained weights for the model? Thank you! @yiyeChen

**Comment by antoalli** [comment]
Hi, sorry for the late reply! I've pushed the checkpoints of L2G with PN2 and DeCo encoders under the folder "checkpoints_L2G". Hope this helps, Antonio

**Comment by Andyyoung0507** [comment]
Thank you very much!
